name: moodlog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  image_picker: ^1.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  flutter_image_compress: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#4F46E5"        # Fondo del icono adaptativo (indigo)
  adaptive_icon_foreground: "assets/icon.png" # Puedes usar la misma imagen
  min_sdk_android: 21                         # Compatibilidad con Android 5+

flutter:
  uses-material-design: true